# Generated by Django 4.0.1 on 2022-01-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pr2user',
            new_name='pruser',
        ),
    ]
